Display rewrite
underground-software/sensehat pull request #45
Opened 2022-01-15 04:34 UTC by charliemirabile

In this series of commits I perform a significant overhaul on the code in `sensehat-display.c`.
Changes:
 - I fixed bug in `sensehat_display_ioctl` where a user could supply gamma values outside of the range 0-31 sending invalid data to the sensehat. The values are now wrapped mod 32 (i.e. only their 5 lsb are considered)
 - I made a small touch up to the `sensehat_display_llseek` function since I felt like the code could be made a bit more clear / self documenting by renaming a few variables
 - I removed the use of temporary buffers to hold the received data from all calls to `copy_from_userspace` (i.e. those in `sensehat_display_write` and `sensehat_display_ioctl`).
   - This has the potential issue that if a user passes a pointer near the edge of their valid memory region and so some amount of data is able to be copied but the copy faults part way through, then a partial update of the sensehat display will occur as opposed to the previous behavior where an error during `copy_from_userspace` would cause the partial changes to never manifest on the display as the syscall would be scrapped before the partial data was copied from temp into the actual vmem or gamma buffer. It does, however, elide an extraneous copy in the case where there is no error.
 - I replaced the userspace interface for the display driver so that the user just directly manages the values they want for each of the 192 bytes (3 for each pixel) and we do nothing more than relay those changes (after wrapping the values mod 32 and applying gamma) directly to the sensehat. I also updated the tests to reflect this new design.

2022-01-19 01:12 UTC, daniel-w-bauman reviewed
Read through, code makes sense and matches the PR description.

2022-01-20 18:15 UTC, theyoyojo requested changes

2022-01-20 18:15 UTC, theyoyojo commented on sensehat-display.c
> +	ret = regmap_bulk_write(sensehat->regmap, SENSEHAT_DISPLAY, display->vmem,
where gamma?????

404 𝛾 not found

2022-01-20 18:32 UTC, theyoyojo approved these changes
lgtm

2022-01-20 18:33 UTC, merged